version: '3.5'
services:
  web:
    build: .
    env_file: .env
    ports:
      - '5000:5000'
    volumes:
      - '.:/app'
  database:
    container_name: postgres
    image: postgres:latest
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql

volumes:
  db_volume:
